### ISSUE TITLE
Have version MAS_EPD105_L8AM105_V06_210705

### ISSUE THREAD

**Issue by zenminimalist** [qwerty12/inkPalm-5-EPD105-root#1]
I know I'm kinda late to the party, but I currently have inkPalm and I'm wanting to root. I check my version and it's MAS_EPD105_L8AM105_V06_210705 not MAS_EPD105_L8AM105_V05_210518. I was wondering if you or anyone has experience with this version and how different it is. V06 <-> V05.

Can I still root? 

And if I can help by somehow dumping my version's boot.img let me know. I just need to know the command and I'll provide them. 😊

**Comment by qwerty12** [comment]
Huh, I don't think I've ever received an update since rooting my inkPalm, so I'm still stuck on 210518... 

To dump your own image, follow [this](https://github.com/qwerty12/inkPalm-5-EPD105-root#or-patching-your-own-image). If the recovery still accepts zips signed with the test key, then that's a good indication Xiaomi don't care. If Magisk successfully patches the image, you'll *probably* be okay. But you should be warned that doing that will write a file to /system, which will probably mean your inkPalm won't be able to receive/install further OTAs regardless of whether you choose to root the phone or not at that point.

**Comment by zenminimalist** [comment]
Thanks for the quick response. So if I do step 1-4 and my device accepts the dump_kernel_to_system_signed.zip it's likely to work? And if it doesn't then I can just delete the dump_kernel_to_system_signed.zip and move on?

I'm not too worried about not receiving any updates. It's not like Andriod 8.1. is going to be updated to 9 or 10 : ) But I'd like to update to 2GB RAM OTA.

**Comment by qwerty12** [comment]
I'd say it's an indicator of Xiaomi's continued indifference to rooting - consider that OTA updates are served over non-secure HTTP and someone can sign their own zips that the inkPalm will accept - but not necessarily a sign everything will be well. Yes, if the recovery refuses to accept the zip file, no changes will have been made.

Fair enough :)

**Comment by zenminimalist** [comment]
Ok thanks. And just to be sure (better safe than sorry 🙂), I do steps 1-12 and do **NOT** continue to "[](https://github.com/qwerty12/inkPalm-5-EPD105-root#using-recovery-to-do-it)Flashing the patched kernel image". Is my understanding correct?

**Comment by qwerty12** [comment]
You have to continue onto the flashing section: steps 1-12 of "patching your own image" will (read; should) get you a Magisk-patched kernel image, but it still needs to be applied to the device after that. I would recommend keeping a copy of your original kernel image (the `/system/bimg.img` file) on your computer.

**Comment by zenminimalist** [comment]
Thanks for the help, Obi-Wan! 🙂

OK, I did something stupid and risky (I totally admit it😇), but it seemed to have worked. I first updated to the newest firmware: MAS_EPD105_L8AM105_V08_220308. And judging from the last few digits it seems to have come out a few days ago. 🤯 For reference: Mine came with version MAS_EPD105_L8AM105_V06_210705 out of the box. 

Can you tell me what to check/look for to confirm that everything is working correctly? That way I can confirm to future users wanting to root with your guide that it works up to this version (or you could also mention it in your guide/Readme)

I checked with a root verifying app that I do have root access. 

BTW: How high do you think the chances are that if I contact the vendor of the eReader and ask them if they would kindly provide us with the translation file and we would then crowed source a proper translation. I could have a friend of mine to it from CN --> EN. I could then do it from EN --> DE....That would allow them to increase their seller base...Just a thought....

Or is there a way to access the system language file and translate that from CN --> EN?

**Comment by qwerty12** [comment]
Glad to hear it worked :)

Honestly, if further updates might not be arriving, it makes sense to install the most recent update you can find. If your root checker says all is well, then I would say you're okay. The guy who made Magisk is extremely smart and over the years put in a ton of effort to make sure various Android devices are supported. If Xiaomi didn't want this device to be rooted, they would simply lock the bootloader.

Not very high at all, in my opinion. Moann (Xiaomi) don't sell this device outside of China, so I can't see them taking on extra work for customers they never wanted. Plus, they don't even provide the kernel source, which they're legally obliged to do under the GPL, so I can't see them providing the code of things they don't have to. Technically, you don't need the code to translate most applications.

You can get the base Android software into English: https://github.com/philips/inkpalm-5-adb-english#change-language-to-english
Of course, the Xiaomi applications won't be in English, but that's what third-party ePub readers are for. It's extremely hard to see on the inkPalm (I used `scrcpy` and guessed what I was pressing), but [MoreLocale](https://play.google.com/store/apps/details?id=jp.co.c_lis.ccl.morelocale) will let you choose languages other than English for the base Android system

**Comment by zenminimalist** [comment]
>Not very high at all, in my opinion. Moann (Xiaomi) don't sell this device outside of China, so I can't see them taking on extra work for customers they never wanted. Plus, they don't even provide the kernel source, which they're legally obliged to do under the GPL, so I can't see them providing the code of things they don't have to. Technically, you don't need the code to translate most applications.

True, all valid points. Sad, though because this little device could have so much potential with a bit more RAM, a better CPU and a clean, lean ROM...

Thanks anyway for your great help and your guide!
