### ISSUE TITLE
Found option to unlock boatloader

### ISSUE THREAD

**Issue by zenminimalist** [qwerty12/inkPalm-5-EPD105-root#2]
I'm not sure if this is relevant to future roots (or making them easier), but I just stumbled upon the option "OEM unlocking" that allows the bootloader to be unlocked in the developer options. 

Are you aware of that? I'm not really that familiar with Andriod per se and its innerworkings, but I'd thought I mention it in case this is s "new" find

**Comment by qwerty12** [comment]
> Are you aware of that? 

From the guide:

> I caused the OEM unlock option to show in developer options (a setprop command of some sort) and I ticked it. Not sure it was needed, or what it changes; the bootloader should already be unlocked to the best of my knowledge. The setting did persist after wiping /data, though. I'm too scared to turn it off.

Though I do wonder why it automatically showed on your device and not mine. Oh well. I don't think enabling the option does anything anyway: if the bootloader was locked, you'd certainly find out during the process of rooting the inkPalm...

**Comment by zenminimalist** [comment]
Ah, OK. I must have overread that part. Just discovered that part. I guess I'm not going to be a good security researcher 😬

**Comment by qwerty12** [comment]
You and me both :D
